version: '3.3'

services:
  backend:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - RUN_MIGRATIONS=1
    command: bash -c "python ./hotel/manage.py migrate && python ./hotel/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  frontend:
    restart: always
    build: ./front
    depends_on:
      - backend


    ports:
        - "3000:3000"

  db:
    container_name: hotel
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hotel
      POSTGRES_PASSWORD: hotel
      POSTGRES_DB: hotel
    image: postgres:13.3
    restart: always